name: Lint

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run unit
      run: npm run unit
